<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GEVW59D07RA24FU" name="com.zs.auto.day09_1102.testcase.login.LoginTest" tests="6" failures="0" timestamp="13 Nov 2019 13:42:50 GMT" time="8.994" errors="1">
  <testcase name="login_fail_case" time="0.369" classname="com.zs.auto.day09_1102.testcase.login.LoginTest"/>
  <testcase name="login_fail_case" time="0.410" classname="com.zs.auto.day09_1102.testcase.login.LoginTest"/>
  <testcase name="login_fail_case" time="0.400" classname="com.zs.auto.day09_1102.testcase.login.LoginTest"/>
  <testcase name="login_fail_case" time="0.950" classname="com.zs.auto.day09_1102.testcase.login.LoginTest"/>
  <testcase name="login_fail_case" time="0.361" classname="com.zs.auto.day09_1102.testcase.login.LoginTest">
    <error type="java.lang.AssertionError" message="expected [非法的手机号111] but found [非法的手机号]">
      <![CDATA[java.lang.AssertionError: expected [非法的手机号111] but found [非法的手机号]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.zs.auto.day09_1102.base.Base.assertElementTextEquals(Base.java:320)
	at com.zs.auto.day09_1102.base.Base.assertElementTextEquals(Base.java:310)
	at com.zs.auto.day09_1102.testcase.login.LoginTest.login_fail_case(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- login_fail_case -->
  <testcase name="login_fail_case" time="6.504" classname="com.zs.auto.day09_1102.testcase.login.LoginTest"/>
</testsuite> <!-- com.zs.auto.day09_1102.testcase.login.LoginTest -->
